export const categories = [
  { value: "clothing", label: "Clothing" },
  { value: "men's wear", label: "Men's Wear" },
  { value: "women's wear", label: "Women's Wear" },
  { value: "accessories", label: "Accessories" },
  { value: "footwear", label: "Footwear" },
  { value: "sportsWear", label: "Sports Wear" },
  { value: "Other", label: "Other" },
];

export const brands = [
  { value: "nike", label: "Nike" },
  { value: "adidas", label: "Adidas" },
  { value: "puma", label: "Puma" },
  { value: "underArmour", label: "Under Armour" },
  { value: "reebok", label: "Reebok" },
  { value: "vans", label: "Vans" },
  { value: "converse", label: "Converse" },
  { value: "levi", label: "Levi's" },
  { value: "gap", label: "Gap" },
  { value: "zara", label: "Zara" },
  { value: "h&m", label: "H&M" },
  { value: "calvinKlein", label: "Calvin Klein" },
  { value: "ralphLauren", label: "Ralph Lauren" },
  { value: "Other", label: "Other" },
];

export const conditions = [
  { value: "new", label: "New" },
  { value: "used", label: "Used" },
  { value: "vintage", label: "Vintage" },
];

export const countries = [
  { value: "United States", label: "United States" },
  { value: "Canada", label: "Canada" },
  { value: "United Kingdom", label: "United Kingdom" },
  { value: "Australia", label: "Australia" },
  { value: "India", label: "India" },
  { value: "Germany", label: "Germany" },
  { value: "France", label: "France" },
  { value: "Japan", label: "Japan" },
  { value: "China", label: "China" },
  { value: "Brazil", label: "Brazil" },
  { value: "Mexico", label: "Mexico" },
  { value: "Pakistan", label: "Pakistan" },
  { value: "Italy", label: "Italy" },
  { value: "Spain", label: "Spain" },
  { value: "Russia", label: "Russia" },
  { value: "South Korea", label: "South Korea" },
  { value: "Netherlands", label: "Netherlands" },
  { value: "Sweden", label: "Sweden" },
  { value: "Norway", label: "Norway" },
  { value: "Switzerland", label: "Switzerland" },
  { value: "South Africa", label: "South Africa" },
  { value: "New Zealand", label: "New Zealand" },
  { value: "Argentina", label: "Argentina" },
  { value: "Chile", label: "Chile" },
  { value: "Colombia", label: "Colombia" },
  { value: "Belgium", label: "Belgium" },
  { value: "Austria", label: "Austria" },
  { value: "Denmark", label: "Denmark" },
  { value: "Finland", label: "Finland" },
  { value: "Ireland", label: "Ireland" },
  { value: "Portugal", label: "Portugal" },
  { value: "Poland", label: "Poland" },
  { value: "Greece", label: "Greece" },
  { value: "Turkey", label: "Turkey" },
  { value: "Saudi Arabia", label: "Saudi Arabia" },
  { value: "United Arab Emirates", label: "United Arab Emirates" },
  { value: "Egypt", label: "Egypt" },
  { value: "Nigeria", label: "Nigeria" },
  { value: "Kenya", label: "Kenya" },
  { value: "Indonesia", label: "Indonesia" },
  { value: "Thailand", label: "Thailand" },
  { value: "Malaysia", label: "Malaysia" },
  { value: "Philippines", label: "Philippines" },
  { value: "Vietnam", label: "Vietnam" },
  { value: "Singapore", label: "Singapore" },
  { value: "Other", label: "Other" },
];

export const sizes = [
  { value: "Extra Small", label: "Extra Small" },
  { value: "Small", label: "Small" },
  { value: "Medium", label: "Medium" },
  { value: "Large", label: "Large" },
  { value: "Extra Large", label: "Extra Large" },
  { value: "2X Large", label: "2X Large" },
  { value: "3X Large", label: "3X Large" },
];

export const colors = [
  { value: "Red", label: "Red" },
  { value: "Blue", label: "Blue" },
  { value: "Green", label: "Green" },
  { value: "Yellow", label: "Yellow" },
  { value: "Black", label: "Black" },
  { value: "White", label: "White" },
  { value: "Purple", label: "Purple" },
  { value: "Pink", label: "Pink" },
  { value: "Orange", label: "Orange" },
  { value: "Gray", label: "Gray" },
  { value: "Brown", label: "Brown" },
  { value: "Cyan", label: "Cyan" },
  { value: "Magenta", label: "Magenta" },
  { value: "Other", label: "Other" },
];
